# Generated by Django 4.0.6 on 2022-07-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default='2022-07-17 17:34:24.651439'),
        ),
    ]
