# Generated by Django 4.0.6 on 2022-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_alter_posts_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default='2022-07-17 17:37:47.181281'),
        ),
    ]
