# Generated by Django 4.0.6 on 2022-07-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0005_alter_posts_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTube',
        ),
    ]
