# Generated by Django 4.0.6 on 2022-08-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0007_usersubjects_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserInfoRepair',
        ),
        migrations.RenameModel(
            old_name='UserSubjects',
            new_name='UserSubjectsRepair',
        ),
    ]
