# Generated by Django 4.0.6 on 2022-08-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
                ('physics', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=80)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.usersubjects')),
            ],
        ),
    ]
